name: Build and deploy

on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  lint:
    name: "helm lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v5
      - name: Replace values in values.yaml
        env:
          IMAGE_NAME: "ghcr.io/${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}"
        run: |
          sed -i -e "s#__IMAGE_NAME__#${IMAGE_NAME}#g" values.yaml
          sed -i -e "s#__TAG__#${GITHUB_SHA}#g" values.yaml
      - uses: BlindfoldedSurgery/github-action-helm@v0.3.0
        with:
          subcommand: lint
          strict: true
          namespace: extmd2html

  build-container-image:
    runs-on: ubuntu-latest
    if: success() && github.event_name == 'pull_request'
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v5
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Build container image
        uses: docker/build-push-action@v5
        with:
          push: false
          context: .
          file: Containerfile
          tags: "ghcr.io/${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}:${{ github.sha }}"

  push-container-image:
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v5
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: Containerfile
          tags: "ghcr.io/${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}:${{ github.sha }}"

  deploy:
    name: "Publish to k8s"
    runs-on: ubuntu-latest
    concurrency: production
    needs: [push-container-image, lint]
    steps:
      - uses: actions/checkout@v4
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v5
      - name: Replace values in values.yaml
        env:
          IMAGE_NAME: "ghcr.io/${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}"
        run: |
          sed -i -e "s#__IMAGE_NAME__#${IMAGE_NAME}#g" values.yaml
          sed -i -e "s#__TAG__#${GITHUB_SHA}#g" values.yaml
      - name: install helm chart
        uses: BlindfoldedSurgery/github-action-helm@v0.3.0
        with:
          subcommand: upgrade
          ref: .
          release_name: extmd2html
          namespace: static
          atomic: true
          install: true
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}

  clean:
    runs-on: ubuntu-latest
    concurrency: cleanup
    continue-on-error: true
    needs: [ deploy ]
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v5
      - name: Clean up old app container images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}
          package-type: container
          min-versions-to-keep: 10
